<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LTIN504051" failures="1" tests="3" name="EdgeTest" time="24.825" errors="0" timestamp="2024-09-18T22:17:56 IST">
  <testcase classname="parameterization.ParallelTesting" name="testLogo" time="0.059"/>
  <testcase classname="parameterization.ParallelTesting" name="getTitle" time="0.016"/>
  <testcase classname="parameterization.ParallelTesting" name="getUrl" time="0.012">
    <failure type="java.lang.AssertionError" message="expected [https://opensource-demo.orangehrmlive.com/] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]">
      <![CDATA[java.lang.AssertionError: expected [https://opensource-demo.orangehrmlive.com/] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]
at parameterization.ParallelTesting.getUrl(ParallelTesting.java:63)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- getUrl -->
</testsuite> <!-- EdgeTest -->
